# Generated by Django 4.2.14 on 2024-07-22 08:14

from django.db import migrations, models
import django.db.models.deletion
import django_tidb.fields


class Migration(migrations.Migration):

    replaces = [('blogs', '0001_initial'), ('blogs', '0002_author_book'), ('blogs', '0003_mymodel'), ('blogs', '0004_alter_comment_id_alter_post_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'tidb_auto_id_cache': 1,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='blogs.author')),
            ],
            options={
                'tidb_auto_id_cache': 1,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.post')),
            ],
        ),
    ]
