# Generated by Django 4.2.14 on 2024-07-22 05:03

from django.db import migrations, models
import django_tidb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
