# Generated by Django 4.2.14 on 2024-07-22 05:36

from django.db import migrations
import django_tidb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=django_tidb.fields.BigAutoRandomField(primary_key=True, range=64, serialize=False, shard_bits=5),
        ),
    ]
